# Generated by Django 3.0.9 on 2020-08-24 17:19

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='saasyprofile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='roles',
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.IntegerField(choices=[(1, 'user'), (5, 'staff'), (10, 'admin')], default=1, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(1, 'user'), (5, 'staff'), (10, 'admin')], default=1, verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
