# Generated by Django 3.0.9 on 2020-08-20 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
