# Generated by Django 3.0.9 on 2020-08-20 20:51

import autoslug.fields
from django.db import migrations
import saasy.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0002_auto_20200820_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=saasy.models.profile.set_user_profile_slug, unique=True),
        ),
    ]
