# Generated by Django 3.0.9 on 2020-08-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0002_auto_20200821_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1),
        ),
    ]
