# Generated by Django 3.0.9 on 2020-08-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0003_project_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Free'), (2, 'Paid')], default=1),
        ),
    ]
