# Generated by Django 3.0.9 on 2020-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0004_auto_20200820_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(1, 'User'), (20, 'Administrator')], default=1, verbose_name='Role'),
        ),
    ]
