# Generated by Django 3.0.9 on 2020-08-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('saasy', '0004_profile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saasy_profiles', to='sites.Site'),
        ),
    ]
