# Generated by Django 3.0.9 on 2020-08-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0005_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='saasy.Project', verbose_name='Project'),
        ),
    ]
