# Generated by Django 3.0.9 on 2020-08-21 00:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saasy', '0005_profile_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('site', 'user')},
        ),
    ]
