# Generated by Django 3.0.9 on 2020-08-21 00:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saasy', '0006_auto_20200821_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='SaasyProfile',
        ),
        migrations.AlterModelOptions(
            name='saasyprofile',
            options={'verbose_name': 'Saasy Profile', 'verbose_name_plural': 'Saasy Profiles'},
        ),
    ]
