# Generated by Django 3.0.9 on 2020-08-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0006_auto_20200820_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamRole',
        ),
    ]
