# Generated by Django 3.0.9 on 2020-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saasy', '0008_teamassignment_teamrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamassignment',
            name='roles',
            field=models.ManyToManyField(to='saasy.TeamRole', verbose_name='Roles'),
        ),
    ]
